import { ReactNode } from "react";
import "@/app/globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        <Header />

        {/* Banner */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
